import Head from 'next/head'
import ProgressBar from '@/components/ProgressBar'
import {useState} from 'react'
import {API_URL,NEXT_URL} from '@/config/index'
import axios from "axios";
import {nanoid} from "nanoid";
import {toast, ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import Link from "next/link";

export default function Home() {
    const [file, setFile] = useState(null)
    const [percentage, setPercentage] = useState(0)
    const [uid, setUid] = useState(new Date().getTime() + nanoid(5))

    const uploadFile = async (e) => {
        const file = e.target.files[0]
        console.log(e.target.files)
        const data = new FormData()
        data.append('files.file', file)
        data.append('data', JSON.stringify({"uid": '1673678308735_64cs'}))
        try {
            const upload_res = await axios.post(`${API_URL}/api/documents`, data, {
                headers: {
                    'Content-Type': 'multipart/form-data'
                },
                onUploadProgress: (progressEvent) => {
                    setPercentage(parseInt(Math.round((progressEvent.loaded * 100) / progressEvent.total)))
                }
            })
            if (upload_res.status === 200) {
                toast.success('File uploaded successfully')
            } else {
                toast.error('File upload failed')
            }
        } catch (e) {
            if (e.response.status === 413) {
                toast.error('File size too large')
            } else if (e.response.status === 400) {
                toast.error(e.response.data.message[0].messages[0].message)
            }
            console.log(e)
        }
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app'/>
                <meta name='viewport' content='width=device-width, initial-scale=1'/>
                <link rel='icon' href='/favicon.ico'/>
            </Head>
            <ToastContainer position='top-center' autoClose={5000} hideProgressBar={false} newestOnTop={false} />
            <main>
                {/* Centered Layout */}
                <div className='max-w-7xl mx-auto py-6 px-2 sm:px-6 lg:px-8 flex flex-col items-center justify-center min-h-screen'>
                    {/* Center div below */}
                    <div className='w-full max-w-md transition-all'>

                        <label className='block text-sm font-medium text-gray-700'>
                            Upload File
                        </label>
                        <div
                            className='mt-1 flex justify-center rounded-md border-2 border-dashed border-gray-300 px-6 pt-5 pb-6'>
                            <div className='space-y-1 text-center'>
                                <svg
                                    className='mx-auto h-12 w-12 text-gray-400'
                                    stroke='currentColor'
                                    fill='none'
                                    viewBox='0 0 48 48'
                                    aria-hidden='true'
                                >
                                    <path
                                        d='M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02'
                                        strokeWidth='2'
                                        strokeLinecap='round'
                                        strokeLinejoin='round'
                                    />
                                </svg>
                                <div className='flex text-sm text-gray-600'>
                                    <form>
                                        <label
                                            htmlFor='file-upload'
                                            className='relative cursor-pointer rounded-md bg-white font-medium text-green-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-green-500 focus-within:ring-offset-2 hover:text-green-500'
                                        >
                                            <span>Upload a file</span>
                                            <input
                                                id='file-upload'
                                                name='file-upload'
                                                type='file'
                                                className='sr-only'
                                                onChange={uploadFile}
                                            />
                                        </label>
                                    </form>

                                    <p className='pl-1'>or drag and drop</p>
                                </div>
                                <p className='text-xs text-gray-500'>Any file up to 10MB</p>
                            </div>
                        </div>
                        {/* Upload bar */}
                        <div className='mt-4'>
                            {percentage > 0 && <ProgressBar percentage={percentage}/>}
                        </div>
                        {/* Show file uid */}
                        {percentage > 0 && (
                            <div>

                                <div className='mt-4'>
                                    <Link href={`/api/documents/${uid}`}>
                                        <p className='text-green-600 hover:text-green-500'>Dowload File</p>
                                    </Link>
                                </div>

                                <div className='mt-4'>
                                    <p>
                                        {NEXT_URL}/api/documents/{uid}
                                    </p>
                                    <button
                                        className='bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded'
                                        onClick={() => {
                                            navigator.clipboard.writeText(`${NEXT_URL}/api/documents/${uid}`)
                                        }}
                                    >
                                        Copy to clipboard
                                    </button>
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </main>
        </>
    )
}
